### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by mirsamantajbakhsh** [Kalivos/ha_openmediavault#6]
First of all thanks for your plugin. I've installed in my HA but in getting the sensor value, it results in following error:
```2020-02-13 03:44:35 ERROR (MainThread) [homeassistant.components.sensor] openmediavault: Error on device update!
Traceback (most recent call last):
  File "HOME_ASSISTANT_DIRECTORY/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 299, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "HOME_ASSISTANT_DIRECTORY/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/home/mirsaman/.homeassistant/custom_components/openmediavault/sensor.py", line 145, in async_update
    self._api.update()
  File "HOME_ASSISTANT_DIRECTORY/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "HOME_ASSISTANT_DIRECTORY/custom_components/openmediavault/sensor.py", line 247, in update
    self.get_system_information()
  File "HOME_ASSISTANT_DIRECTORY/custom_components/openmediavault/sensor.py", line 229, in get_system_information
    self.format_system_information()
  File "HOME_ASSISTANT_DIRECTORY/custom_components/openmediavault/sensor.py", line 237, in format_system_information
    prop = attr_key['name'].lower().replace(" ", "_")
TypeError: string indices must be integers
```
The error indicates that:
**File "HOME_ASSISTANT_DIRECTORY/custom_components/openmediavault/sensor.py", line 237, in format_system_information
prop = attr_key['name'].lower().replace(" ", "_")
TypeError: string indices must be integers**
I wanted to ask if the **attr_key['name']** should be changed to some kind of integer value?

Thanks in advanced

**Comment by dkalinai** [comment]
Having exactly the same issue here.

**Comment by dkalinai** [comment]
This is the response i am getting from the sensor: 

`2020-03-22 09:23:45 DEBUG (MainThread) [custom_components.openmediavault.sensor] Response from OMV get_system_information():  {'response': {'ts': 1584861824, 'time': 'Sun Mar 22 09:23:44 2020', 'hostname': 'raspberrynas', 'version': '5.3.8-1 (Usul)', 'cpuModelName': 'ARMv7 Processor rev 4 (v7l)', 'cpuUsage': 5.037783375314862, 'memTotal': '971055104', 'memUsed': '182824960', 'kernel': 'Linux 4.19.97-v7+', 'uptime': '0 days 0 hours 35 minutes 39 seconds', 'loadAverage': '0.07, 0.09, 0.16', 'configDirty': False, 'rebootRequired': False, 'pkgUpdatesAvailable': False}, 'error': None}`

**Comment by dkalinai** [comment]
Created a PR where this has been fixed. At least locally for me it now works flawlessly :) Thanks to the original creator for doing most of the work.
